### ISSUE TITLE
Pyinput error iterating x

### ISSUE THREAD

**Issue by DudeChill** [DudeChill/Pybomb#1]
when i try to move the player across the matrix array i get this error
```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\_util\__init__.py", line 228, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\keyboard\_win32.py", line 290, in _process
    self.on_release(key)
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\_util\__init__.py", line 144, in inner
    if f(*args) is False:
       ^^^^^^^^
  File "C:\Users\alexg\Bomberman\Bomberman.py", line 37, in on_key_release
    right()
  File "C:\Users\alexg\Bomberman\Bomberman.py", line 31, in right
    x+=1
    ^
UnboundLocalError: cannot access local variable 'x' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\alexg\Bomberman\Bomberman.py", line 47, in <module>
    listener.join()
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\_util\__init__.py", line 276, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\_util\__init__.py", line 228, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\keyboard\_win32.py", line 290, in _process
    self.on_release(key)
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynput\_util\__init__.py", line 144, in inner
    if f(*args) is False:
       ^^^^^^^^
  File "C:\Users\alexg\Bomberman\Bomberman.py", line 37, in on_key_release
    right()
  File "C:\Users\alexg\Bomberman\Bomberman.py", line 31, in right
    x+=1
    ^
UnboundLocalError: cannot access local variable 'x' where it is not associated with a value
```

**Comment by DudeChill** [comment]
fixed it
